[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mini-capstone"
version = "0.1.0"
dependencies = []

# This tells modern backends to look inside the src folder
[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src"]
